---
title: "Lifespans of Jesus' Ancestors"
author: "Peyton John Hall"
date: "03/14/2024"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Required Libraries}
# Clear the environment
rm(list=ls())

# Load necessary libraries
library(ggplot2)
library(readr)
```

```{r Read CSV}
# MacBook Pro Note: hover over file + option + command + c  + command + v
Lifespans <- read_csv("/Users/peytonhall/Desktop/BiblionGenealogy/QueriedResults/Individuals With Documented Lifespans.csv")
# Lifespans
```

```{r Lifespan Analysis}
# Clean the names (data type string)
cleaned_names <- gsub("'Eth-'Ha'adham \\(a.k.a. Adam\\)", "Adam", Lifespans$Name)
cleaned_names <- gsub("Abraham \\(a.k.a. Abram\\)", "Abraham", cleaned_names)
cleaned_names <- gsub("Jacob \\(a.k.a. Israel\\)", "Jacob", cleaned_names)
cleaned_names <- gsub("David, King of Israel \\(Undivided Kingdom\\)", "David", cleaned_names)

# Create a data frame with cleaned names
Lifespans_cleaned <- data.frame(Name = cleaned_names, Lifespan_Years = Lifespans$`Lifespan Years`)

# Reorder the data frame based on the Generation column
Lifespans_cleaned <- Lifespans_cleaned[order(Lifespans$Generation), ]

# Reorder the factor levels of the "Name" variable based on the "Generation" column
Lifespans_cleaned$Name <- factor(Lifespans_cleaned$Name, levels = Lifespans_cleaned$Name[order(Lifespans$Generation)])

# Generate a bar graph with 90° tilted x-axis labels, a labeled x-axis & y-axis, and a centered title.
ggplot(Lifespans_cleaned, aes(x = Name, y = Lifespan_Years)) +
  geom_bar(stat = "identity", color = "black", fill = "maroon") +
  labs(title = "Lifespans of Jesus' Ancestors", x = "Names", y = "Lifespan Years",
       caption = "Sources (KJV): Ge 5:3-10, 5:12-23, 5:25-31, 9:29, 11:10-25, 11:32, 25:7, 35:28, 47:28, 2 Sa 5:3-4") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        plot.title = element_text(hjust = 0.5),
        plot.caption = element_text(hjust = 0.5))
```
